name: "Report review request"
fields:
- type: "input"
  attributes:
    label: "Report title"
    description: "Title of the report"
  validations:
    required: true
- type: "dropdown"
  attributes:
    label: "Type of report"
    description: "Select one"
    options:
    - label: "Report"
      required: false
    - label: "Other"
      required: false
  validations:
    required: true
- type: "dropdown"
  attributes:
    label: "Submission type"
    description: "Select one..."
    options:
    - label: "New report"
      required: false
    - label: "Resubmission"
      required: false
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Message to editors"
    description: "Please describe the type of report you are submitting, along with a short 1-2 line description. Include anything that the editors should be aware of when reviewing your submission."
  validations:
    required: true
- type: "input"
  attributes:
    label: "Git repository of the source file"
    description: "For example, the github link where the .qmd source file is stored, in the form https://github.com/username/repository"
  validations:
    required: true
- type: "input"
  attributes:
    label: "Author's Github username"
    description: "Your Github user handle. For example for @username, enter \"username\""
  validations:
    required: true
- type: "checkboxes"
  attributes:
    label: "Declaration"
    options:
    - label: "I certify that I have the authority to submit this report on behalf of its authors"
      required: true
    - label: "I certify that I have read and understood the review code of conduct"
      required: true
    - label: "I certify that I have read and understood the description of the review process"
      required: true
  validations:
    required: false
